apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-altinn-gateway_vestfoldfylke_no
      fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vestfoldfylke-no.flyt.*"
        
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "vestfoldfylke-no.altinn.*"
        
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
        
      - op: add
        path: "/spec/url/basePath"
        value: "/beta/vestfoldfylke-no"
        
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/vestfoldfylke-no/api/altinn"
      
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.org-id"
          value: "vestfoldfylke-no"
          
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.altinn.api.base-url"
          value: "http://fint-altinn-service:8080/beta"
      
      - op: add
        path: "/spec/env/-"
        value:
          name: "logging.level.no.fintlabs"
          value: "DEBUG"
          
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/vestfoldfylke-no/actuator/health"

    target:
      kind: Application
      name: fint-flyt-altinn-gateway
