fint:
  application-id: fint-flyt-altinn-gateway
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  flyt:
    sourceapplication:
      retentionTimeInDays: 30
logging:
  level:
    no.fintlabs.cache.ehcache.FintEhCacheEventLogger: WARN
server:
  error:
    include-message: always
  max-http-request-header-size: 40KB
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  codec:
    max-in-memory-size: 100MB
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-resource-server
      - flyt-file-client