fint:
  org-id: ofk.no
  flyt:
    file-service-url: http://localhost:8091
    resource-server:
      security:
        api:
          external:
            enabled: true
            authorized-client-ids: 5
    instance-gateway:
      check-integration-exists: false
  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
server:
  port: 8999
logging:
  level:
    no.fintlabs.altinnInstanceController: DEBUG